server:
  port: 8084

spring:
  application:
    name: inventory-service

  config:
    import: optional:configserver:${CONFIG_SERVER_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}